In [2]:
#importing libraries
import numpy as np
import pandas as pd

In [3]:
#Importing dataset
df = pd.read_csv(r"C:\Users\Hrithik shukla\ML_Projects\uci-parkinsons\parkinsons.data.csv",header=0,index_col=0)
df.head()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
name                                                                      
phon_R01_S01_1      119.992       157.302        74.997         0.00784   
phon_R01_S01_2      122.400       148.650       113.819         0.00968   
phon_R01_S01_3      116.682       131.111       111.555         0.01050   
phon_R01_S01_4      116.676       137.871       111.366         0.00997   
phon_R01_S01_5      116.014       141.781       110.655         0.01284   

                MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  \
name                                                               
phon_R01_S01_1           0.00007   0.00370   0.00554     0.01109   
phon_R01_S01_2           0.00008   0.00465   0.00696     0.01394   
phon_R01_S01_3           0.00009   0.00544   0.00781     0.01633   
phon_R01_S01_4           0.00009   0.00502   0.00698     0.01505   
phon_R01_S01_5           0.00011   0.00655   0.00908     0.01966   

                MDVP:Shimmer  MDVP:Shimmer(dB)  ...  Shimmer:DDA      NHR  \
name                                            ...                         
phon_R01_S01_1       0.04374             0.426  ...      0.06545  0.02211   
phon_R01_S01_2       0.06134             0.626  ...      0.09403  0.01929   
phon_R01_S01_3       0.05233             0.482  ...      0.08270  0.01309   
phon_R01_S01_4       0.05492             0.517  ...      0.08771  0.01353   
phon_R01_S01_5       0.06425             0.584  ...      0.10470  0.01767   

                   HNR      RPDE       DFA   spread1   spread2        D2  \
name                                                                       
phon_R01_S01_1  21.033  0.414783  0.815285 -4.813031  0.266482  2.301442   
phon_R01_S01_2  19.085  0.458359  0.819521 -4.075192  0.335590  2.486855   
phon_R01_S01_3  20.651  0.429895  0.825288 -4.443179  0.311173  2.342259   
phon_R01_S01_4  20.644  0.434969  0.819235 -4.117501  0.334147  2.405554   
phon_R01_S01_5  19.649  0.417356  0.823484 -3.747787  0.234513  2.332180   

                     PPE  status  
name                              
phon_R01_S01_1  0.284654       1  
phon_R01_S01_2  0.368674       1  
phon_R01_S01_3  0.332634       1  
phon_R01_S01_4  0.368975       1  
phon_R01_S01_5  0.410335       1  

[5 rows x 23 columns]

In [4]:
#Dimensions
df.shape
"""
Rows=195
Columns = 23
"""

'\nRows=195\nColumns = 23\n'

In [5]:
#Checking null values
df.isnull().sum()

MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
status              0
dtype: int64

In [6]:
df.describe(include="all")

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count   195.000000    195.000000    195.000000      195.000000   
mean    154.228641    197.104918    116.324631        0.006220   
std      41.390065     91.491548     43.521413        0.004848   
min      88.333000    102.145000     65.476000        0.001680   
25%     117.572000    134.862500     84.291000        0.003460   
50%     148.790000    175.829000    104.315000        0.004940   
75%     182.769000    224.205500    140.018500        0.007365   
max     260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  ...  Shimmer:DDA         NHR         HNR        RPDE  \
count        195.000000  ...   195.000000  195.000000  195.000000  195.000000   
mean           0.282251  ...     0.046993    0.024847   21.885974    0.498536   
std            0.194877  ...     0.030459    0.040418    4.425764    0.103942   
min            0.085000  ...     0.013640    0.000650    8.441000    0.256570   
25%            0.148500  ...     0.024735    0.005925   19.198000    0.421306   
50%            0.221000  ...     0.038360    0.011660   22.085000    0.495954   
75%            0.350000  ...     0.060795    0.025640   25.075500    0.587562   
max            1.302000  ...     0.169420    0.314820   33.047000    0.685151   

              DFA     spread1     spread2          D2         PPE      status  
count  195.000000  195.000000  195.000000  195.000000  195.000000  195.000000  
mean     0.718099   -5.684397    0.226510    2.381826    0.206552    0.753846  
std      0.055336    1.090208    0.083406    0.382799    0.090119    0.431878  
min      0.574282   -7.964984    0.006274    1.423287    0.044539    0.000000  
25%      0.674758   -6.450096    0.174351    2.099125    0.137451    1.000000  
50%      0.722254   -5.720868    0.218885    2.361532    0.194052    1.000000  
75%      0.761881   -5.046192    0.279234    2.636456    0.252980    1.000000  
max      0.825288   -2.434031    0.450493    3.671155    0.527367    1.000000  

[8 rows x 23 columns]

In [7]:
#Data types
df["status"]= df["status"].astype(int)
df.dtypes

MDVP:Fo(Hz)         float64
MDVP:Fhi(Hz)        float64
MDVP:Flo(Hz)        float64
MDVP:Jitter(%)      float64
MDVP:Jitter(Abs)    float64
MDVP:RAP            float64
MDVP:PPQ            float64
Jitter:DDP          float64
MDVP:Shimmer        float64
MDVP:Shimmer(dB)    float64
Shimmer:APQ3        float64
Shimmer:APQ5        float64
MDVP:APQ            float64
Shimmer:DDA         float64
NHR                 float64
HNR                 float64
RPDE                float64
DFA                 float64
spread1             float64
spread2             float64
D2                  float64
PPE                 float64
status                int32
dtype: object

In [42]:
#Splitting X and Y
X = df.values[:,:-1]
Y = df.values[:,-1]
Y = Y.astype(int)

In [43]:
#Checking shapes of X and Y     
print(X.shape)
print(Y.shape)

(195, 22)
(195,)


In [44]:
#Standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)

X= scaler.transform(X)

In [45]:
print(X)

[[-0.82929965 -0.43616456 -0.95203729 ...  0.48047686 -0.21053082
   0.86888575]
 [-0.77097169 -0.53097409 -0.05772056 ...  1.31118546  0.27507712
   1.80360503]
 [-0.90947638 -0.7231683  -0.10987483 ...  1.01768236 -0.10362861
   1.40266141]
 ...
 [ 0.49557839  0.47010361 -0.96839309 ... -0.81807931  0.78033848
  -0.83241014]
 [ 1.07876114  2.19004398 -0.95417967 ... -0.22906571 -0.63700298
  -0.92610456]
 [ 1.45481664  0.69224632 -0.88348115 ... -0.43085284  0.45480231
  -0.64505466]]


In [46]:
from sklearn.model_selection  import train_test_split
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,
                                                    random_state=10)

In [47]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(156, 22)
(39, 22)
(156,)
(39,)


In [48]:
"""
1] Decison tree
2] SVM
3] KNN
4] Logistic Regression
"""

'\n1] Decison tree\n2] SVM\n3] KNN\n4] Logistic Regression\n'

# KNN

In [49]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
metric='manhattan')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 9  2]
 [ 0 28]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.82      0.90        11
           1       0.93      1.00      0.97        28

    accuracy                           0.95        39
   macro avg       0.97      0.91      0.93        39
weighted avg       0.95      0.95      0.95        39

Accuracy of the model:  0.9487179487179487


In [51]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(2,31):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="manhattan")
    model_KNN.fit(X_train, Y_train)
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  0.9487179487179487 for K-Value: 2
Accuracy is  0.9743589743589743 for K-Value: 3
Accuracy is  0.9743589743589743 for K-Value: 4
Accuracy is  0.9743589743589743 for K-Value: 5
Accuracy is  0.9743589743589743 for K-Value: 6
Accuracy is  0.9230769230769231 for K-Value: 7
Accuracy is  0.9743589743589743 for K-Value: 8
Accuracy is  0.9487179487179487 for K-Value: 9
Accuracy is  0.9487179487179487 for K-Value: 10
Accuracy is  0.9487179487179487 for K-Value: 11
Accuracy is  0.9487179487179487 for K-Value: 12
Accuracy is  0.9487179487179487 for K-Value: 13
Accuracy is  0.9487179487179487 for K-Value: 14
Accuracy is  0.9230769230769231 for K-Value: 15
Accuracy is  0.9487179487179487 for K-Value: 16
Accuracy is  0.9487179487179487 for K-Value: 17
Accuracy is  0.9487179487179487 for K-Value: 18
Accuracy is  0.9487179487179487 for K-Value: 19
Accuracy is  0.9487179487179487 for K-Value: 20
Accuracy is  0.9230769230769231 for K-Value: 21
Accuracy is  0.9230769230769231 for K-Value: 22


In [52]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

3 : 0.9743589743589743
4 : 0.9743589743589743
5 : 0.9743589743589743
6 : 0.9743589743589743
8 : 0.9743589743589743


In [53]:
# Tuned KNN Classifier
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=4,
metric='manhattan')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[11  0]
 [ 1 27]]

Classification report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.96      0.98        28

    accuracy                           0.97        39
   macro avg       0.96      0.98      0.97        39
weighted avg       0.98      0.97      0.97        39

Accuracy of the model:  0.9743589743589743


# SVM

In [54]:
from sklearn.svm import SVC
svc_model = SVC(kernel='rbf',gamma=0.01,C=20)
svc_model.fit(X_train,Y_train)
Y_pred = svc_model.predict(X_test)
print(list(Y_pred))

[1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0]


In [55]:
svc_model.score(X_train,Y_train)

0.9102564102564102

In [56]:
from sklearn.metrics import confusion_matrix
Y_pred_new = svc_model.predict(X_train)
confusion_matrix(Y_train,Y_pred_new)

array([[ 24,  13],
       [  1, 118]], dtype=int64)

In [57]:
from sklearn import svm

svc_model = svm.SVC()

parameter_space = {
    'kernel': ["linear","rbf","poly","sigmoid"],
    'gamma': [0.1,0.01,0.001],
    'C': [1,5,8,10,20]
}
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svc_model, parameter_space, n_jobs=-1, cv=5)

In [58]:
clf.fit(X_train,Y_train)
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}


In [59]:
#Tuned Model 
from sklearn.svm import SVC
svc_model = SVC(kernel='rbf',gamma=0.1,C=10)
svc_model.fit(X_train,Y_train)
Y_pred = svc_model.predict(X_test)
#print(list(Y_pred))

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
#Confusion Matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[11  0]
 [ 0 28]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        28

    accuracy                           1.00        39
   macro avg       1.00      1.00      1.00        39
weighted avg       1.00      1.00      1.00        39



# Logistic Regression

In [61]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier = LogisticRegression()

#fitting training data to the model
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
print(Y_pred)

[1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0
 1 0]


In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cfm = confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc= accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[11  0]
 [ 1 27]]
Classification report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.96      0.98        28

    accuracy                           0.97        39
   macro avg       0.96      0.98      0.97        39
weighted avg       0.98      0.97      0.97        39

Accuracy of the model:  0.9743589743589743


# Decision Tree

In [63]:
#Predictingusing the Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree = DecisionTreeClassifier(criterion="gini",random_state=10,
                                           splitter="best")
#splitter = best/random(might get larger tree)
#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred = model_DecisionTree.predict(X_test)

print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 0 0 1 0
 1 0]
[(1, 1), (1, 1), (1, 1), (1, 1), (0, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0)]


In [64]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
#Confusion Matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 9  2]
 [ 1 27]]
0.9230769230769231
              precision    recall  f1-score   support

           0       0.90      0.82      0.86        11
           1       0.93      0.96      0.95        28

    accuracy                           0.92        39
   macro avg       0.92      0.89      0.90        39
weighted avg       0.92      0.92      0.92        39



In [65]:
model_DecisionTree.score(X_train,Y_train)

1.0

In [66]:
#Predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest = RandomForestClassifier(n_estimators=200,random_state=10)

#fit the model on the data and predict the value
model_RandomForest.fit(X_train,Y_train)

Y_pred = model_RandomForest.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#Confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[10  1]
 [ 0 28]]
0.9743589743589743
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.97      1.00      0.98        28

    accuracy                           0.97        39
   macro avg       0.98      0.95      0.97        39
weighted avg       0.98      0.97      0.97        39



In [67]:
algorithms = ["SVM","Tuned SVM","KNN","Tuned KNN","Logistic Regression","Decision Tree","Random Forest"]
acc = [91.02,100.0,94.87,97.43,97.43,92.30,97.43]
Report = pd.DataFrame({"Algorithm":algorithms,"Accuracy":acc},index=np.arange(1,8,1))
Report

Algorithm  Accuracy
1                  SVM     91.02
2            Tuned SVM    100.00
3                  KNN     94.87
4            Tuned KNN     97.43
5  Logistic Regression     97.43
6        Decision Tree     92.30
7        Random Forest     97.43